name: Workflow de plusieurs jobs
on: 
  push:
    path: 
      - .github/worflows/workflow6.yml
    
  workflow_dispatch:
     jobs:
       test: 
         runs-on: ubuntu-latest
         steps:
           - name: affiche test
             run: echo "test" 
       build:
         runs-on: ubuntu-latest
         steps:
           - name: affiche build
             run: echo build
