name: commandes
on: push
jobs: 
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: afficher début
        run: echo "Début"
      - name: qui suis-je
        run: whoami
      - name: reprtoire de travail
        run: pwd
      - name: afficher les fichiers 
        run: ls -la
      - name: afficher la fin
        run: echo "Fin"
