name: commandes
on: push
jobs: 
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: afficher début
        run: |
          echo "Début"
          whoami
          pwd
          ls -la
          echo "Fin"
