name: Infos sur le context

on:
  push:
    paths:
      - .github/workflows/workflow11.yml
jobs:
  afficher_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le nom du repo
        run: echo "Nom du repo :" ${{ github.run_number }}
