name: Workflow avec trois jobs
on:
  push:
    paths:
      - .github/workflows/workflow7.yml
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: afficher install
        run: echo install
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: afficher test
        run: echo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: afficher build
        run: echo build
