name: workflow sur les conditions simples

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Toujours
        run: echo "Toujours"

      - name: Seulement sur main
        if: github.ref == 'refs/heads/main'
        run: echo "Sur la branche main"
